//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsmFicheroWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignaturas
    {
        public Asignaturas()
        {
            this.Horarios = new HashSet<Horarios>();
            this.Noticias = new HashSet<Noticias>();
            this.UsuarioAsignatura = new HashSet<UsuarioAsignatura>();
        }
    
        public byte CodAsig { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Horarios> Horarios { get; set; }
        public virtual ICollection<Noticias> Noticias { get; set; }
        public virtual ICollection<UsuarioAsignatura> UsuarioAsignatura { get; set; }
    }
}
