//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsmFicheroWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamentos
    {
        public Departamentos()
        {
            this.Carreras = new HashSet<Carreras>();
        }
    
        public byte IdDepartamento { get; set; }
        public string RutJefeDepto { get; set; }
        public string NombreDepartamento { get; set; }
    
        public virtual ICollection<Carreras> Carreras { get; set; }
    }
}
