//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsmFicheroWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hora
    {
        public Hora()
        {
            this.Horarios = new HashSet<Horarios>();
        }
    
        public byte CodHora { get; set; }
        public int HoraInicio { get; set; }
        public int HoraTermino { get; set; }
    
        public virtual ICollection<Horarios> Horarios { get; set; }
    }
}
