//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsmFicheroWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horarios
    {
        public byte CodAsignatura { get; set; }
        public byte Modificado { get; set; }
        public string Paralelo { get; set; }
        public byte Dia { get; set; }
        public byte CodHora { get; set; }
        public Nullable<int> CodHoraFinal { get; set; }
        public Nullable<byte> CodSala { get; set; }
        public Nullable<int> RutProfesor { get; set; }
        public Nullable<System.DateTime> FechaModi { get; set; }
    
        public virtual Asignaturas Asignaturas { get; set; }
        public virtual Hora Hora { get; set; }
        public virtual Salas Salas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
