//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsmFicheroWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FicheroBDEntities1 : DbContext
    {
        public FicheroBDEntities1()
            : base("name=FicheroBDEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Asignaturas> Asignaturas { get; set; }
        public DbSet<Carreras> Carreras { get; set; }
        public DbSet<Departamentos> Departamentos { get; set; }
        public DbSet<Edificios> Edificios { get; set; }
        public DbSet<Hora> Hora { get; set; }
        public DbSet<Horarios> Horarios { get; set; }
        public DbSet<Noticias> Noticias { get; set; }
        public DbSet<Salas> Salas { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<UsuarioAsignatura> UsuarioAsignatura { get; set; }
        public DbSet<UsuarioCarrera> UsuarioCarrera { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
    }
}
