//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsmFicheroWeb
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Horarios = new HashSet<Horarios>();
            this.Noticias = new HashSet<Noticias>();
            this.UsuarioAsignatura = new HashSet<UsuarioAsignatura>();
            this.UsuarioCarrera = new HashSet<UsuarioCarrera>();
        }

        public int Rut { get; set; }
        public string Dv { get; set; }
        public Nullable<byte> TipoUser { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Fono { get; set; }
        public string Contraseña { get; set; }
        public Nullable<byte> IdCarrera { get; set; }
        public Nullable<byte> IdNoticias { get; set; }
        public string HorarioAtencion { get; set; }
    
        public virtual ICollection<Horarios> Horarios { get; set; }
        public virtual ICollection<Noticias> Noticias { get; set; }
        public virtual ICollection<UsuarioAsignatura> UsuarioAsignatura { get; set; }
        public virtual ICollection<UsuarioCarrera> UsuarioCarrera { get; set; }
    }
}
