//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsmFicheroWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioCarrera
    {
        public int Rut { get; set; }
        public byte IdCarrera { get; set; }
        public Nullable<byte> TipoProfesor { get; set; }
    
        public virtual Carreras Carreras { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
