//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsmFicheroWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioAsignatura
    {
        public int RutUsuario { get; set; }
        public byte CodAsignatura { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<byte> Semestre { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Nota1 { get; set; }
        public Nullable<int> Nota2 { get; set; }
        public Nullable<int> Nota3 { get; set; }
        public Nullable<int> Nota4 { get; set; }
        public Nullable<int> Nota5 { get; set; }
        public string Paralelo { get; set; }
        public Nullable<int> RutProfesor { get; set; }
    
        public virtual Asignaturas Asignaturas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
